"""fix

Revision ID: dc2a946af37f
Revises: 220923bc6a86
Create Date: 2026-05-02 19:18:10.537660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2a946af37f'
down_revision = '220923bc6a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('order_index')
        batch_op.drop_column('document_url')
        batch_op.drop_column('description')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_published')
        batch_op.drop_column('total_duration')

    # ### end Alembic commands ###
